apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cyojhynui-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6e80161b9da813082b19b49907da5f04a25797f2@sha256:1090b20ae774289f1dd746fbcc173eead2622b8d70a6b6a6320620daf4cc3ac9
          name: container-image
